server:
  port: 7071
spring:
  application:
    name: wayne-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.174:8848
        namespace: a6b85d6c-a02c-49eb-9560-8499f47d2439
feign:
  sentinel:
    enabled: true